import { Mission } from "./mission-object";


export const MISSIONS: Mission[] = [
    {
        id: 1,
        type: "electric",
        loc: { lat: -28.025, lng: 140.887 },
        level: 1,
        desc: "变压器损坏",
        time: new Date().toISOString(),
        isFixed: true,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 2,
        type: "electric",
        loc: { lat: -28.026, lng: 140.887 },
        level: 2,
        desc: "电线暴露",
        time: new Date().toISOString(),
        isFixed: false,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 3,
        type: "electric",
        loc: { lat: -28.024, lng: 140.888 },
        level: 3,
        desc: "保险丝熔断",
        time: new Date().toISOString(),
        isFixed: true,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 4,
        type: "electric",
        loc: { lat: -28.024, lng: 140.889 },
        level: 1,
        desc: "变压器损坏",
        time: new Date().toISOString(),
        isFixed: false,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 5,
        type: "electric",
        loc: { lat: -28.025, lng: 140.888 },
        level: 2,
        desc: "电线暴露",
        time: new Date().toISOString(),
        isFixed: true,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 6,
        type: "electric",
        loc: { lat: -28.025, lng: 140.889 },
        level: 3,
        desc: "保险丝熔断",
        time: new Date().toISOString(),
        isFixed: true,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
    {
        id: 7,
        type: "electric",
        loc: { lat: -28.026, lng: 140.888 },
        level: 1,
        desc: "变压器损坏",
        time: new Date().toISOString(),
        isFixed: false,
        image: '/asset/imgs/view.jpg',
        casualties: "一人受伤，一人死亡",
    },
]